unit TestuVenda;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, Vcl.Dialogs, System.Generics.Collections, uVenda,
  System.SysUtils;

type
  // Test methods for class TVenda

  TestTVenda = class(TTestCase)
  strict private
    FVenda: TVenda;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcularVenda;
  end;

implementation

procedure TestTVenda.SetUp;
begin
  FVenda := TVenda.Create;
end;

procedure TestTVenda.TearDown;
begin
  FVenda.Free;
  FVenda := nil;
end;

procedure TestTVenda.TestCalcularVenda;
var
  pPrecoLt: Double;
  pTipoValor: TTipoValor;
  pValor: Double;
begin
  pPrecoLt := 2.50;
  pTipoValor := tpValorVenda;
  pValor := 25.00;
  FVenda.CalcularVenda(pValor, pTipoValor, pPrecoLt);

  CheckEquals(10, FVenda.QtdLitro);
  CheckEquals(3.25, FVenda.VlrImposto);
  CheckEquals(10, FVenda.QtdLitro);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTVenda.Suite);
end.

